# Tốc độ xử lý của NumPy

Gấp 10 đến 100 lần so với Python thuần túy

In [60]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 842 ms, sys: 229 ms, total: 1.07 s
Wall time: 1.17 s


In [61]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2


CPU times: user 23.1 ms, sys: 11.8 ms, total: 34.9 ms
Wall time: 49.4 ms


In [62]:
my_arr[1:10]
my_arr.shape
my_arr.ndim

1

# Mảng đa chiều (N-dimensional array object)

NumPy cho phép thực hiện các phép toán trên mảng tương tự các phép toán trên số thực

In [63]:
np.random.randn(1,2)

array([[-0.57094628, -0.63936281]])

In [64]:
data = np.random.randn(2, 3)

In [65]:
data[1,2]

0.10936274268933638

In [66]:
data * 2

array([[-0.41396833,  0.52971563,  2.49430456],
       [-0.31210314,  1.04509911,  0.21872549]])

In [67]:
data + data

array([[-0.41396833,  0.52971563,  2.49430456],
       [-0.31210314,  1.04509911,  0.21872549]])

# Cách khởi tạo mảng trong NumPy

Sử dụng phương thức array() để chuyển mảng trong Python qua mảng trong NumPy

In [68]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [69]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [70]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Các thuộc tính của đối tượng ndarray

In [71]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [72]:
arr1.ndim

1

In [73]:
arr1.shape

(5,)

In [74]:
arr1.dtype

dtype('float64')

In [75]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
arr2.ndim

2

In [77]:
arr2.shape

(2, 4)

In [78]:
arr2.dtype

dtype('int64')

In [79]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [80]:
# tao ndarray tu data2 voi dtype=float64
arr3 = np.array(data2, dtype=np.float64)
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

# Cách khởi tạo mảng trong NumPy

Khởi tạo mảng đa chiều với các phần tử ‘0’

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
arr4 = np.empty((2, 3, 3))
arr4

array([[[1.36914791, 3.63704363, 0.31234918],
        [0.20319237, 3.21009262, 1.80844997],
        [1.72232829, 2.29580863, 1.39468194]],

       [[5.49918792, 0.87243807, 2.17318488],
        [2.22240187, 1.2578684 , 5.11736374],
        [2.92655002, 1.51787676, 0.21358324]]])

In [84]:
np.empty((2, 2), dtype=np.float64)

array([[6. , 7.5],
       [8. , 1. ]])

In [85]:
# type upcasting
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [86]:
# type downcasting
arr3 = np.array([1.5, 2.9, 3.0], dtype=np.int64)
arr3

array([1, 2, 3])

Kiểu dữ liệu trong NumPy

In [87]:
numeric_strings = np.array(['1.25', '-9.6', '42'])

In [88]:
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [89]:
numeric_strings1 = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [90]:
numeric_strings1

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [90]:
numeric_strings2 = numeric_strings1.astype(float)
numeric_strings2

array([ 1.25, -9.6 , 42.  ])

# Toán tử vecto hoá (element-wise)

NumPy cung cấp các toán tử để thực hiện các phép tính trên mảng mà không cần sử dụng các lệnh vòng lặp. Người dùng NumPy gọi đây là vector hóa (vectorization).

In [91]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print(arr)
print(arr*arr)
print(arr-arr)
print(1/arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [96]:
print(arr)
arr2 = np.array([[0., 4., 1.], [7., 2., 3.]]) 
print(arr2)
tmp = arr>arr2
tmp

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 4. 1.]
 [7. 2. 3.]]


array([[ True, False,  True],
       [False,  True,  True]])

Để thao tác với các phần tử hay các tập con trong mảng của NumPy, ta thao tác như List của Python

In [98]:
arr = np.arange(10) 
print(arr)
print(arr[5]) 
print(arr[5:-1])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]


In [112]:
data = np.random.randn(7, 4) # shape (7,4), ndim=2
print(data)
row3 = data[1:4] # extract 3 hang (dim 0) co chi so 1 den 3 cua data
col3 = data[:,1:4] # extract 3 cot (dim 1) co chi so 1 den 3 cua data
rl23 = data[1:3,1:4] # extract 2 hang 1,2 va 3 cot 1 den 3 cua data
rl23

[[-1.59312692  0.36707436 -0.66364838 -0.0464924 ]
 [-0.64845515 -0.32075309  1.03343433  1.34207126]
 [ 0.2833927   0.33916721  1.57887748  0.55109705]
 [ 0.83667721 -0.0813518  -0.98181307  1.20107858]
 [-0.2266992  -2.33043475 -1.6798627  -0.09923112]
 [-0.38379966  1.10640225  0.86915695 -0.79798384]
 [ 0.81078376  0.4425251  -0.35169041 -0.30958919]]


array([[-0.32075309,  1.03343433,  1.34207126],
       [ 0.33916721,  1.57887748,  0.55109705]])

Dùng mảng Boolean để tạo mảng con lấy ra từ 1 mảng khác nếu như 2 mảng có cùng chiều dài

In [119]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', ' Joe', 'Joe']) # shape (7,), ndim=1
data = np.random.randn(7, 4) # shape (7,4), ndim=2
print(names)
print('----')
print(data)
print('----')
bArr = (names=='Bob') # shape (7,), ndim=1
print(bArr)
print('----')
# tao mang moi tu mang data gom cac hang (dim 0) co chi so tuong ung voi vị tri names='Bob'
new_arr = data[bArr]
new_arr

['Bob' 'Joe' 'Will' 'Bob' 'Will' ' Joe' 'Joe']
----
[[ 1.07326399  2.40234781 -0.24702785 -0.5649236 ]
 [ 2.44851852  0.72587862  1.28405005  1.13754037]
 [-0.37414087 -0.33291561  0.26477883 -2.06435796]
 [-1.0855521   0.12675861  0.04767929  0.00472422]
 [-0.97935793  0.96546988 -2.14358902 -0.3407346 ]
 [ 0.81969206  0.93388282  0.02575212  2.28357652]
 [-0.48208844 -1.20611095 -0.14952544  1.25454495]]
----
[ True False False  True False False False]
----


array([[ 1.07326399,  2.40234781, -0.24702785, -0.5649236 ],
       [-1.0855521 ,  0.12675861,  0.04767929,  0.00472422]])

In [120]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
data = np.random.randn(7, 4) 
print(names)
print(data)
bArr = (names=='Bob')
print(bArr)
# tao mang moi tu mang data gom cac cot (dim 1) co chi so tuong ung voi vị tri names='Bob'
new_arr = data[:,bArr]
new_arr

['Bob' 'Joe' 'Will' 'Bob']
[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]
[ True False False  True]


array([[ 0.19480759, -1.00409384],
       [-0.48667153, -1.12682358],
       [-1.7339251 , -0.1037882 ],
       [-0.05424126, -0.72562403],
       [-1.00043868, -0.11301861],
       [-0.48052778,  0.10648897],
       [ 0.635065  , -2.3002476 ]])

In [122]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', ' Joe', 'Joe']) # shape (7,), ndim=1
print(data)
data[names == 'Bob', 2:]

[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]


array([[-0.49005068, -1.00409384],
       [ 1.7167484 , -0.72562403]])

In [123]:
tmp = data[names == 'Bob', 3]
print(tmp)
print(tmp.shape)
print(tmp.ndim)

[-1.00409384 -0.72562403]
(2,)
1


In [115]:
# tuy nhien
tmp = data[names == 'Bob', 3:4]
print(tmp)
print(tmp.shape)
print(tmp.ndim)

[[-0.56064414]
 [ 0.0575538 ]]
(2, 1)
2


In [114]:
tmp.shape

(2,)

In [124]:
data < 0

array([[False, False,  True,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True]])

In [117]:
print(data)
data[data<0] = 0 # gan cac phan tu < 0 bang 0
print(data)

[[ 1.01877829  0.82616959 -0.93350126 -0.56064414]
 [-0.35029027  0.78344508  2.10992952 -0.10712143]
 [ 0.32193369  0.59530245 -0.53178139 -2.02309498]
 [-0.03459249 -0.7323536   0.54517855  0.0575538 ]
 [ 0.93679149  0.28060197 -1.2229251  -1.1334753 ]
 [-1.05767781 -0.6536159  -0.76183843  0.43448742]
 [ 1.36836894  2.02029875  0.29357661 -1.60249456]]
[[1.01877829 0.82616959 0.         0.        ]
 [0.         0.78344508 2.10992952 0.        ]
 [0.32193369 0.59530245 0.         0.        ]
 [0.         0.         0.54517855 0.0575538 ]
 [0.93679149 0.28060197 0.         0.        ]
 [0.         0.         0.         0.43448742]
 [1.36836894 2.02029875 0.29357661 0.        ]]


# Fancy Indexing

NumPy cho phép tạo 1 mảng con theo chỉ mục cho trước

In [126]:
names = np.array(['Tuan', 'Phuong', 'Khoi', 'Hieu', 'Duy' , 'Thang', 'Duc'])
print(names)
# tao mang moi tu mang names gom cac ptu co index 0,5,4 cua dim0
print(names[[0,5,4]])

['Tuan' 'Phuong' 'Khoi' 'Hieu' 'Duy' 'Thang' 'Duc']
['Tuan' 'Thang' 'Duy']


In [125]:
data

array([[ 0.19480759,  1.1170717 , -0.49005068, -1.00409384],
       [-0.48667153, -1.48944268,  0.79132013, -1.12682358],
       [-1.7339251 ,  0.91453725,  0.96692051, -0.1037882 ],
       [-0.05424126, -0.72040116,  1.7167484 , -0.72562403],
       [-1.00043868,  0.10577565,  0.05390387, -0.11301861],
       [-0.48052778,  0.67136122, -0.8586809 ,  0.10648897],
       [ 0.635065  , -0.1201173 , -1.92080774, -2.3002476 ]])

In [132]:
print(data)
print('----')
tmp = data[:,[3,0]] # lay ra cot 3 va cot 0
print(tmp)
print('----')
tmp.shape

[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]
----
[[-1.00409384  0.19480759]
 [-1.12682358 -0.48667153]
 [-0.1037882  -1.7339251 ]
 [-0.72562403 -0.05424126]
 [-0.11301861 -1.00043868]
 [ 0.10648897 -0.48052778]
 [-2.3002476   0.635065  ]]
----


(7, 2)

In [133]:
print(data)
print('----')
tmp = data[[0,1,2,3],[0,1,2,3]] # lay ra data[0,0], data[1,1],...
print(tmp)
print('----')
tmp.shape

[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]
----
[ 0.19480759 -1.48944268  0.96692051 -0.72562403]
----


(4,)

In [135]:
# chuyen array 1x32 thanh arr 8x4
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [137]:
print(arr[[1, 5, 7, 2]]) # lay 4 hang 1,5,7,2
print()
print(arr[[1, 5, 7, 2]] [:, :]) # lay 4 hang 1,5,7,2 va tat ca cot
print(arr[[1, 5, 7, 2]] [:, [0, 3]]) # lay 4 hang 1,5,7,2 va cot 0, 3
print(arr[:,[0,3]] [[1, 5, 7, 2]]) # lay 4 hang 1,5,7,2 va cot 0, 3

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]]
[[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]]


Ma trận chuyển vị

In [200]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [201]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [202]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [138]:
arr = np.arange(16).reshape((2, 8))
print(arr)
print('-----')
print(arr.T)
print('-----')
print(arr.transpose())
print('-----')
print(arr.swapaxes(0, 1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]


In [151]:
arr1 = np.arange(16).reshape((2, 8))
arr2 = np.arange(16).reshape((2, 8))
arr_sum1 = arr1 + arr2
arr_sum2 = np.add(arr1,arr2)
arr_sum1 == arr_sum2

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [155]:
np.random.seed(1)
x = np.random.rand(4)
print(x)
np.random.seed(0)
x = np.random.rand(4)
print(x)
np.random.seed(1)
x = np.random.rand(4)
print(x)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
[0.5488135  0.71518937 0.60276338 0.54488318]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]


In [156]:
mydict = {1: 'Tran A', 'chuoi': 'vang', 3.14: 'pi', "NNLT": 'python'}
mylist2 = ['a','b','c','d','e']
z = zip(mydict,mylist2)
for l1, l2 in z:
    print('key ', l1, 'co value la', mydict[l1], 'dc zip voi', l2)

key  1 co value la Tran A dc zip voi a
key  chuoi co value la vang dc zip voi b
key  3.14 co value la pi dc zip voi c
key  NNLT co value la python dc zip voi d


In [151]:
from numpy.linalg import inv
X = np.random.randn(2, 2)
mat = X.T.dot(X)
print(mat)
print(inv(mat))
print(mat.dot(inv(mat)))

[[3.76352626 0.72588267]
 [0.72588267 0.4979884 ]]
[[ 0.36962316 -0.53877369]
 [-0.53877369  2.79341141]]
[[1.00000000e+00 9.73694331e-17]
 [4.51784418e-17 1.00000000e+00]]
